# Import Libraries and Dataset

In [94]:
import pandas as pd
import numpy as np
import statsbombpy as sb

In [95]:
womens_world_cup_stats = pd.read_csv(
    '/Users/gui/womens_world_cup_2023_statsbomb_final.csv'
)

In [96]:
womens_world_cup_stats

,match_id,match_date,team,opponent,stage,goals_for,goals_against,result,points,possession_pct,...,goals_after_turnover,set_piece_goals,tackles,tackles_won,interceptions,blocks,clearances,recoveries,saves,clean_sheet
0,3893787,2023-07-20,New Zealand Women's,Norway Women's,Group,1,0,W,3,57.781529,...,0.0,1,27,13.0,8,28,24,72,2,1
1,3893787,2023-07-20,Norway Women's,New Zealand Women's,Group,0,1,L,0,42.218471,...,0.0,0,23,11.0,12,31,42,60,1,0
2,3893788,2023-07-20,Australia Women's,Republic of Ireland Women's,Group,1,0,W,3,58.013378,...,0.0,0,19,11.0,5,23,33,72,1,1
3,3893788,2023-07-20,Republic of Ireland Women's,Australia Women's,Group,0,1,L,0,41.986622,...,0.0,0,26,15.0,8,23,17,57,1,0
4,3893789,2023-07-21,Philippines Women's,Switzerland Women's,Group,0,2,L,0,30.212373,...,0.0,0,14,5.0,13,20,33,53,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,3904629,2023-08-16,England Women's,Australia Women's,Semi-finals,3,1,W,3,49.971523,...,1.0,1,19,12.0,7,16,30,51,3,0
124,3906389,2023-08-19,Australia Women's,Sweden Women's,Third-place,0,2,L,0,52.821967,...,0.0,0,18,11.0,17,27,9,66,3,0
125,3906389,2023-08-19,Sweden Women's,Australia Women's,Third-place,2,0,W,3,47.178033,...,1.0,0,26,16.0,12,31,29,65,4,1
126,3906390,2023-08-20,England Women's,Spain Women's,Final,0,1,L,0,44.284665,...,0.0,0,25,13.0,7,24,18,54,4,0
127,3906390,2023-08-20,Spain Women's,England Women's,Final,1,0,W,3,55.715335,...,0.0,0,19,13.0,8,20,36,71,3,1

# Explore Dataset

In [98]:
womens_world_cup_stats.shape

(128, 39)

In [99]:
womens_world_cup_stats.columns

Index(['match_id', 'match_date', 'team', 'opponent', 'stage', 'goals_for',
       'goals_against', 'result', 'points', 'possession_pct', 'passes',
       'pass_accuracy_pct', 'shots', 'shots_on_target', 'shot_accuracy_pct',
       'xG', 'xG_per_shot', 'goals_minus_xG', 'conversion_pct', 'big_chances',
       'key_passes', 'corners', 'crosses', 'progressive_passes',
       'progressive_carries', 'final_third_entries', 'box_entries',
       'high_turnovers', 'shots_after_turnover', 'goals_after_turnover',
       'set_piece_goals', 'tackles', 'tackles_won', 'interceptions', 'blocks',
       'clearances', 'recoveries', 'saves', 'clean_sheet'],
      dtype='object')

In [100]:
list(womens_world_cup_stats.columns)

['match_id',
 'match_date',
 'team',
 'opponent',
 'stage',
 'goals_for',
 'goals_against',
 'result',
 'points',
 'possession_pct',
 'passes',
 'pass_accuracy_pct',
 'shots',
 'shots_on_target',
 'shot_accuracy_pct',
 'xG',
 'xG_per_shot',
 'goals_minus_xG',
 'conversion_pct',
 'big_chances',
 'key_passes',
 'corners',
 'crosses',
 'progressive_passes',
 'progressive_carries',
 'final_third_entries',
 'box_entries',
 'high_turnovers',
 'shots_after_turnover',
 'goals_after_turnover',
 'set_piece_goals',
 'tackles',
 'tackles_won',
 'interceptions',
 'blocks',
 'clearances',
 'recoveries',
 'saves',
 'clean_sheet']

In [101]:
womens_world_cup_stats.dtypes

match_id                  int64
match_date               object
team                     object
opponent                 object
stage                    object
goals_for                 int64
goals_against             int64
result                   object
points                    int64
possession_pct          float64
passes                    int64
pass_accuracy_pct       float64
shots                     int64
shots_on_target           int64
shot_accuracy_pct       float64
xG                      float64
xG_per_shot             float64
goals_minus_xG          float64
conversion_pct          float64
big_chances               int64
key_passes                int64
corners                   int64
crosses                   int64
progressive_passes      float64
progressive_carries     float64
final_third_entries     float64
box_entries             float64
high_turnovers          float64
shots_after_turnover    float64
goals_after_turnover    float64
set_piece_goals           int64
tackles                   int64
tackles_won             float64
interceptions             int64
blocks                    int64
clearances                int64
recoveries                int64
saves                     int64
clean_sheet               int64
dtype: object

In [102]:
womens_world_cup_stats.isna().sum()

match_id                0
match_date              0
team                    0
opponent                0
stage                   0
goals_for               0
goals_against           0
result                  0
points                  0
possession_pct          0
passes                  0
pass_accuracy_pct       0
shots                   0
shots_on_target         0
shot_accuracy_pct       2
xG                      0
xG_per_shot             2
goals_minus_xG          0
conversion_pct          2
big_chances             0
key_passes              0
corners                 0
crosses                 0
progressive_passes      0
progressive_carries     0
final_third_entries     0
box_entries             0
high_turnovers          0
shots_after_turnover    0
goals_after_turnover    0
set_piece_goals         0
tackles                 0
tackles_won             0
interceptions           0
blocks                  0
clearances              0
recoveries              0
saves                   0
clean_sheet             0
dtype: int64

In [103]:
womens_world_cup_stats.isna().any().any()

True

## Initial observations

- The dataset contains 110 rows and 38 columns.
- Each row corresponds to a single match_id.
- The dataset includes information about teams, scores, match dates, competition stages and metadata that will be useful for linking match events.

# Explore Competition

In [106]:
teams = womens_world_cup_stats["team"].unique()

In [107]:
len(teams)

32

In [108]:
teams

array(["New Zealand Women's", "Norway Women's", "Australia Women's",
       "Republic of Ireland Women's", "Philippines Women's",
       "Switzerland Women's", "Canada Women's", "Nigeria Women's",
       "Costa Rica Women's", "Spain Women's", "United States Women's",
       "Vietnam Women's", "Japan Women's", 'Zambia W', "England Women's",
       "Haiti Women's", "China PR Women's", "Denmark Women's",
       "South Africa Women's", "Sweden Women's", "Netherlands Women's",
       "Portugal Women's", "France Women's", "Jamaica Women's",
       "Germany Women's", "Morocco Women's", "Argentina Women's",
       "Italy Women's", "Brazil Women's", "Panama Women's",
       "Colombia Women's", "Korea Republic Women's"], dtype=object)

In [109]:
team_names = {
    'NZL': 'New Zealand',
    'NOR': 'Norway',
    'AUS': 'Australia',
    'IRL': 'Ireland',
    'NGA': 'Nigeria',
    'CAN': 'Canada',
    'PHI': 'Philippines',
    'SUI': 'Switzerland',
    'ESP': 'Spain',
    'CRC': 'Costa Rica',
    'ZMB': 'Zambia',
    'JPN': 'Japan',
    'ENG': 'England',
    'HAI': 'Haiti',
    'DEN': 'Denmark',
    'CHN': 'China',
    'USA': 'United States',
    'VIE': 'Vietnam',
    'NED': 'Netherlands',
    'POR': 'Portugal',
    'FRA': 'France',
    'JAM': 'Jamaica',
    'SWE': 'Sweden',
    'RSA': 'South Africa',
    'GER': 'Germany',
    'MAR': 'Morocco',
    'BRA': 'Brazil',
    'PAN': 'Panama',
    'COL': 'Colombia',
    'KOR': 'South Korea',
    'ITA': 'Italy',
    'ARG': 'Argentina'
}

womens_world_cup_stats['team'] = womens_world_cup_stats['team'].replace(team_names)
womens_world_cup_stats['opponent'] = womens_world_cup_stats['opponent'].replace(team_names)

In [110]:
womens_world_cup_stats[['team', 'opponent']].head(10)

                          team                     opponent
0          New Zealand Women's               Norway Women's
1               Norway Women's          New Zealand Women's
2            Australia Women's  Republic of Ireland Women's
3  Republic of Ireland Women's            Australia Women's
4          Philippines Women's          Switzerland Women's
5          Switzerland Women's          Philippines Women's
6               Canada Women's              Nigeria Women's
7              Nigeria Women's               Canada Women's
8           Costa Rica Women's                Spain Women's
9                Spain Women's           Costa Rica Women's

In [111]:
womens_world_cup_stats

,match_id,match_date,team,opponent,stage,goals_for,goals_against,result,points,possession_pct,...,goals_after_turnover,set_piece_goals,tackles,tackles_won,interceptions,blocks,clearances,recoveries,saves,clean_sheet
0,3893787,2023-07-20,New Zealand Women's,Norway Women's,Group,1,0,W,3,57.781529,...,0.0,1,27,13.0,8,28,24,72,2,1
1,3893787,2023-07-20,Norway Women's,New Zealand Women's,Group,0,1,L,0,42.218471,...,0.0,0,23,11.0,12,31,42,60,1,0
2,3893788,2023-07-20,Australia Women's,Republic of Ireland Women's,Group,1,0,W,3,58.013378,...,0.0,0,19,11.0,5,23,33,72,1,1
3,3893788,2023-07-20,Republic of Ireland Women's,Australia Women's,Group,0,1,L,0,41.986622,...,0.0,0,26,15.0,8,23,17,57,1,0
4,3893789,2023-07-21,Philippines Women's,Switzerland Women's,Group,0,2,L,0,30.212373,...,0.0,0,14,5.0,13,20,33,53,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,3904629,2023-08-16,England Women's,Australia Women's,Semi-finals,3,1,W,3,49.971523,...,1.0,1,19,12.0,7,16,30,51,3,0
124,3906389,2023-08-19,Australia Women's,Sweden Women's,Third-place,0,2,L,0,52.821967,...,0.0,0,18,11.0,17,27,9,66,3,0
125,3906389,2023-08-19,Sweden Women's,Australia Women's,Third-place,2,0,W,3,47.178033,...,1.0,0,26,16.0,12,31,29,65,4,1
126,3906390,2023-08-20,England Women's,Spain Women's,Final,0,1,L,0,44.284665,...,0.0,0,25,13.0,7,24,18,54,4,0
127,3906390,2023-08-20,Spain Women's,England Women's,Final,1,0,W,3,55.715335,...,0.0,0,19,13.0,8,20,36,71,3,1

In [112]:
teams = womens_world_cup_stats["team"].unique()

In [113]:
teams

array(["New Zealand Women's", "Norway Women's", "Australia Women's",
       "Republic of Ireland Women's", "Philippines Women's",
       "Switzerland Women's", "Canada Women's", "Nigeria Women's",
       "Costa Rica Women's", "Spain Women's", "United States Women's",
       "Vietnam Women's", "Japan Women's", 'Zambia W', "England Women's",
       "Haiti Women's", "China PR Women's", "Denmark Women's",
       "South Africa Women's", "Sweden Women's", "Netherlands Women's",
       "Portugal Women's", "France Women's", "Jamaica Women's",
       "Germany Women's", "Morocco Women's", "Argentina Women's",
       "Italy Women's", "Brazil Women's", "Panama Women's",
       "Colombia Women's", "Korea Republic Women's"], dtype=object)

In [114]:
list(teams)

["New Zealand Women's",
 "Norway Women's",
 "Australia Women's",
 "Republic of Ireland Women's",
 "Philippines Women's",
 "Switzerland Women's",
 "Canada Women's",
 "Nigeria Women's",
 "Costa Rica Women's",
 "Spain Women's",
 "United States Women's",
 "Vietnam Women's",
 "Japan Women's",
 'Zambia W',
 "England Women's",
 "Haiti Women's",
 "China PR Women's",
 "Denmark Women's",
 "South Africa Women's",
 "Sweden Women's",
 "Netherlands Women's",
 "Portugal Women's",
 "France Women's",
 "Jamaica Women's",
 "Germany Women's",
 "Morocco Women's",
 "Argentina Women's",
 "Italy Women's",
 "Brazil Women's",
 "Panama Women's",
 "Colombia Women's",
 "Korea Republic Women's"]

## List the teams that did not pass the Group Stage

In [116]:
womens_world_cup_stats['stage'].unique()

array(['Group', 'Round of 16', 'Quarter-finals', 'Semi-finals',
       'Third-place', 'Final'], dtype=object)

## List the teams that did not pass the R16

In [118]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == 'R16']['team'].unique()

array([], dtype=object)

## List the teams that ended up in the QF

In [120]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == 'QF']['team'].unique()

array([], dtype=object)

## List the teams that ended up in the SF

In [122]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == 'SF']['team'].unique()

array([], dtype=object)

## List the teams that ended up in the 3rd

In [124]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == '3rd']['team'].unique()

array([], dtype=object)

## List the teams that ended up in the Final

In [126]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == 'Final']['team'].unique()

array(["England Women's", "Spain Women's"], dtype=object)

### How many games there were in the Group Stage?

In [128]:
womens_world_cup_stats[womens_world_cup_stats['stage'] == 'Group']['match_id'].nunique()

48

In [129]:
womens_world_cup_stats['stage'].value_counts()

stage
Group             96
Round of 16       16
Quarter-finals     8
Semi-finals        4
Third-place        2
Final              2
Name: count, dtype: int64

In [130]:
womens_world_cup_stats[
    womens_world_cup_stats['stage'] == 'Group'
]['match_id'].nunique()

48